### See https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md for comprehensive
### documentation of the options in this file

[buildPlans.IosevkaBlogger]      # <IosevkaBlogger> is your plan name
family = "Iosevka Blogger"        # Font menu family name
spacing = "fontconfig-mono"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "slab"
noCvSs = true
exportGlyphNames = false

###################################################################################################
# Configure variants

# Optional; Whether to inherit a `ss##` variant
  [buildPlans.IosevkaBlogger.variants]
  inherits = "ss14"

# Optional; Configure single character's variant
[buildPlans.IosevkaBlogger.variants.design]
g = 'single-storey-serifless'

# Optional; Configure single character's variant for Upright and Oblique; Overrides [design]
[buildPlans.IosevkaBlogger.variants.upright]
i = 'zshaped'
l = 'zshaped'

# Optional; Configure single character's variant for Italic only; Overrides [design]
[buildPlans.IosevkaBlogger.variants.italic]
i = 'tailed-serifed'
l = 'tailed-serifed'

# End variant section
###################################################################################################

###################################################################################################
# Configure ligations

[buildPlans.IosevkaBlogger.ligations]
inherits = "javascript"   # Optional; inherits an existing ligation set

# End ligation section
###################################################################################################


###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
[buildPlans.IosevkaBlogger.weights.Regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.

[buildPlans.IosevkaBlogger.weights.Book]
shape = 450
menu  = 450  # Use 450 here to name the font's weight "Book"
css   = 450

[buildPlans.IosevkaBlogger.weights.Bold]
shape = 700
menu  = 700
css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# When this section is absent, all slopes would be built.

[buildPlans.IosevkaBlogger.slopes.Upright]
angle = 0             # Angle in degrees. Valid range [0, 15]
shape = "upright"     # Slope grade used for shape selection.  `upright` | `oblique` | `italic`
menu  = "upright"     # Slope grade used for naming.           `upright` | `oblique` | `italic`
css   = "normal"      # Slope grade used for webfont CSS.      `normal`  | `oblique` | `italic`

[buildPlans.IosevkaBlogger.slopes.Oblique]
angle = 9.4
shape = "oblique"
menu  = "oblique"
css   = "oblique"

[buildPlans.IosevkaBlogger.slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"
# End slope section
###################################################################################################


# End compatibility ligatures section
###################################################################################################

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

[buildPlans.IosevkaBlogger.metricOverride]
leading = 1250
winMetricAscenderPad = 0
winMetricDescenderPad = 0
powerlineScaleY = 1
powerlineScaleX = 1
powerlineShiftY = 0
powerlineShiftX = 0

# End metric override section
###################################################################################################
